@echo off
rm -f run_report.txt
rm -f listing.txt
call runprog t6p10d3 run_report.txt listing.txt
call runprog t6p1p1d1 run_report.txt listing.txt
call runprog t6p1p1d2 run_report.txt listing.txt
call runprog t6p1p2d1 run_report.txt listing.txt
call runprog t6p1p2d2 run_report.txt listing.txt
call runprog t6p1p2d3 run_report.txt listing.txt
call runprog t6p1p3d1 run_report.txt listing.txt
call runprog t6p1p3d2 run_report.txt listing.txt
call runprog t6p1p5d1 run_report.txt listing.txt
call runprog t6p1p5d2 run_report.txt listing.txt
call runprog t6p1p6d1 run_report.txt listing.txt
call runprog t6p1p6d2 run_report.txt listing.txt
call runprog t6p1p6d3 run_report.txt listing.txt
call runprog t6p1p7d1 run_report.txt listing.txt
call runprog t6p1p7d2 run_report.txt listing.txt
call runprog t6p1p7d3 run_report.txt listing.txt
call runprog t6p1p8d1 run_report.txt listing.txt
call runprog t6p1p8d2 run_report.txt listing.txt
call runprog t6p1p9d1 run_report.txt listing.txt
call runprog t6p1p9d2 run_report.txt listing.txt
call runprog t6p1p9d3 run_report.txt listing.txt
call runprog t6p2p1d1 run_report.txt listing.txt
call runprog t6p2p1d2 run_report.txt listing.txt
call runprog t6p2p2d1 run_report.txt listing.txt
call runprog t6p2p2d2 run_report.txt listing.txt
call runprog t6p2p2d3 run_report.txt listing.txt
call runprog t6p2p2d4 run_report.txt listing.txt
call runprog t6p2p2d5 run_report.txt listing.txt
call runprog t6p2p2d6 run_report.txt listing.txt
call runprog t6p2p2d7 run_report.txt listing.txt
call runprog t6p3d1 run_report.txt listing.txt
call runprog t6p4p1d1 run_report.txt listing.txt
call runprog t6p4p2p2d1 run_report.txt listing.txt
call runprog t6p4p2p2d2 run_report.txt listing.txt
call runprog t6p4p2p2d3 run_report.txt listing.txt
call runprog t6p4p2p2d4 run_report.txt listing.txt
call runprog t6p4p2p2d5 run_report.txt listing.txt
call runprog t6p4p2p2d6 run_report.txt listing.txt
call runprog t6p4p2p2d7 run_report.txt listing.txt
call runprog t6p4p2p2d8 run_report.txt listing.txt
call runprog t6p4p2p3d1 run_report.txt listing.txt
call runprog t6p4p2p3d2 run_report.txt listing.txt
call runprog t6p4p2p3d3 run_report.txt listing.txt
call runprog t6p4p2p3d4 run_report.txt listing.txt
call runprog t6p4p2p4d1 run_report.txt listing.txt
call runprog t6p4p2p4d2 run_report.txt listing.txt
call runprog t6p4p3p1d1 run_report.txt listing.txt
call runprog t6p4p3p1d2 run_report.txt listing.txt
call runprog t6p4p3p2d1 run_report.txt listing.txt
call runprog t6p4p3p2d2 run_report.txt listing.txt
call runprog t6p4p3p2d3 run_report.txt listing.txt
call runprog t6p4p3p3d1 run_report.txt listing.txt
call runprog t6p4p3p3d17 run_report.txt listing.txt
call runprog t6p4p3p3d2 run_report.txt listing.txt
call runprog t6p4p3p3d3 run_report.txt listing.txt
call runprog t6p4p3p3d4 run_report.txt listing.txt
call runprog t6p4p3p3d5 run_report.txt listing.txt
call runprog t6p4p3p3d6 run_report.txt listing.txt
call runprog t6p4p3p3d7 run_report.txt listing.txt
call runprog t6p4p3p4d1 run_report.txt listing.txt
call runprog t6p4p3p4d2 run_report.txt listing.txt
call runprog t6p4p3p5d1 run_report.txt listing.txt
call runprog t6p4p3p5d10 run_report.txt listing.txt
call runprog t6p4p3p5d11 run_report.txt listing.txt
call runprog t6p4p3p5d12 run_report.txt listing.txt
call runprog t6p4p3p5d2 run_report.txt listing.txt
call runprog t6p4p3p5d3 run_report.txt listing.txt
call runprog t6p4p3p5d4 run_report.txt listing.txt
call runprog t6p4p3p5d5 run_report.txt listing.txt
call runprog t6p4p3p5d6 run_report.txt listing.txt
call runprog t6p4p3p5d7 run_report.txt listing.txt
call runprog t6p4p3p5d8 run_report.txt listing.txt
call runprog t6p4p3p5d9 run_report.txt listing.txt
call runprog t6p4p4d1 run_report.txt listing.txt
call runprog t6p4p5d1 run_report.txt listing.txt
call runprog t6p4p5d2 run_report.txt listing.txt
call runprog t6p4p5d3 run_report.txt listing.txt
call runprog t6p4p5d4 run_report.txt listing.txt
call runprog t6p4p5d5 run_report.txt listing.txt
call runprog t6p4p5d6 run_report.txt listing.txt
call runprog t6p4p6d1 run_report.txt listing.txt
call runprog t6p4p6d2 run_report.txt listing.txt
call runprog t6p4p6d3 run_report.txt listing.txt
call runprog t6p5p1d1 run_report.txt listing.txt
call runprog t6p5p3p2d1 run_report.txt listing.txt
call runprog t6p5p5d1 run_report.txt listing.txt
call runprog t6p6p1d1 run_report.txt listing.txt
call runprog t6p6p1d2 run_report.txt listing.txt
call runprog t6p6p2d1 run_report.txt listing.txt
call runprog t6p6p2d2 run_report.txt listing.txt
call runprog t6p6p2d3 run_report.txt listing.txt
call runprog t6p6p2d4 run_report.txt listing.txt
call runprog t6p6p3p1d1 run_report.txt listing.txt
call runprog t6p6p3p1d2 run_report.txt listing.txt
call runprog t6p6p3p1d3 run_report.txt listing.txt
call runprog t6p6p3p1d4 run_report.txt listing.txt
call runprog t6p6p3p3d1 run_report.txt listing.txt
call runprog t6p6p3p3d2 run_report.txt listing.txt
call runprog t6p6p3p3d3 run_report.txt listing.txt
call runprog t6p6p3p3d6 run_report.txt listing.txt
call runprog t6p6p3p4d1 run_report.txt listing.txt
call runprog t6p6p3p4d2 run_report.txt listing.txt
call runprog t6p6p3p5d1 run_report.txt listing.txt
call runprog t6p6p4p1d1 run_report.txt listing.txt
call runprog t6p6p4p1d2 run_report.txt listing.txt
call runprog t6p6p5p2d1 run_report.txt listing.txt
call runprog t6p6p5p2d2 run_report.txt listing.txt
call runprog t6p6p5p2d3 run_report.txt listing.txt
call runprog t6p6p5p3d1 run_report.txt listing.txt
call runprog t6p6p5p3d15 run_report.txt listing.txt
call runprog t6p6p5p3d18 run_report.txt listing.txt
call runprog t6p6p5p3d19 run_report.txt listing.txt
call runprog t6p6p5p3d2 run_report.txt listing.txt
call runprog t6p6p5p3d20 run_report.txt listing.txt
call runprog t6p6p5p3d22 run_report.txt listing.txt
call runprog t6p6p5p4d1 run_report.txt listing.txt
call runprog t6p6p6p2d1 run_report.txt listing.txt
call runprog t6p6p6p2d2 run_report.txt listing.txt
call runprog t6p6p6p2d3 run_report.txt listing.txt
call runprog t6p6p6p3d1 run_report.txt listing.txt
call runprog t6p6p6p4d1 run_report.txt listing.txt
call runprog t6p6p6p4d2 run_report.txt listing.txt
call runprog t6p6p6p4d3 run_report.txt listing.txt
call runprog t6p6p6p5d1 run_report.txt listing.txt
call runprog t6p6p6p5d2 run_report.txt listing.txt
call runprog t6p7p1d1 run_report.txt listing.txt
call runprog t6p7p1d10 run_report.txt listing.txt
call runprog t6p7p1d2 run_report.txt listing.txt
call runprog t6p7p1d6 run_report.txt listing.txt
call runprog t6p7p1d7 run_report.txt listing.txt
call runprog t6p7p1d8 run_report.txt listing.txt
call runprog t6p7p1d9 run_report.txt listing.txt
call runprog t6p7p2p2d1 run_report.txt listing.txt
call runprog t6p7p2p2d2 run_report.txt listing.txt
call runprog t6p7p2p2d3 run_report.txt listing.txt
call runprog t6p7p2p2d4 run_report.txt listing.txt
call runprog t6p7p2p3d1 run_report.txt listing.txt
call runprog t6p7p2p4d1 run_report.txt listing.txt
call runprog t6p7p2p4d2 run_report.txt listing.txt
call runprog t6p7p2p4d5 run_report.txt listing.txt
call runprog t6p7p2p4d6 run_report.txt listing.txt
call runprog t6p7p2p5d1 run_report.txt listing.txt
call runprog t6p7p2p5d2 run_report.txt listing.txt
call runprog t6p7p2p5d3 run_report.txt listing.txt
call runprog t6p8p2p1d1 run_report.txt listing.txt
call runprog t6p8p2p4d1 run_report.txt listing.txt
call runprog t6p8p3p10d1 run_report.txt listing.txt
call runprog t6p8p3p10d2 run_report.txt listing.txt
call runprog t6p8p3p10d3 run_report.txt listing.txt
call runprog t6p8p3p10d4 run_report.txt listing.txt
call runprog t6p8p3p10d5 run_report.txt listing.txt
call runprog t6p8p3p10d6 run_report.txt listing.txt
call runprog t6p8p3p10d8 run_report.txt listing.txt
call runprog t6p8p3p4d1 run_report.txt listing.txt
call runprog t6p8p3p5d1 run_report.txt listing.txt
call runprog t6p8p3p5d2 run_report.txt listing.txt
call runprog t6p8p3p7d1 run_report.txt listing.txt
call runprog t6p8p3p7d2 run_report.txt listing.txt
call runprog t6p8p3p7d3 run_report.txt listing.txt
call runprog t6p8p3p8d1 run_report.txt listing.txt
call runprog t6p8p3p8d2 run_report.txt listing.txt
call runprog t6p8p3p9d1 run_report.txt listing.txt
call runprog t6p8p3p9d2 run_report.txt listing.txt
call runprog t6p8p3p9d3 run_report.txt listing.txt
call runprog t6p8p3p9d4 run_report.txt listing.txt
call runprog t6p9d1 run_report.txt listing.txt
call runprog t6p9d2 run_report.txt listing.txt
call runprog t6p9p1d1 run_report.txt listing.txt
call runprog t6p9p1d2 run_report.txt listing.txt
call runprog t6p9p1d3 run_report.txt listing.txt
call runprog t6p9p2d1 run_report.txt listing.txt
call runprog t6p9p3d1 run_report.txt listing.txt
call runprog t6p9p3p1d1 run_report.txt listing.txt
call runprog t6p9p3p3d1 run_report.txt listing.txt
call runprog t6p9p3p4d1 run_report.txt listing.txt
call runprog t6p9p3p5p1d1 run_report.txt listing.txt
call runprog t6p9p3p5p2d1 run_report.txt listing.txt
call runprog t6p9p3p7d1 run_report.txt listing.txt
call runprog t6p9p4d1 run_report.txt listing.txt
