@echo off
rm -f run_report.txt
rm -f listing.txt
echo DEV report file >> run_report.txt
echo. >> run_report.txt
echo Examine file for files with zero errors or that have "DEVIATES" at >> run_report.txt
echo the end. >> run_report.txt
echo. >> run_report.txt
call runprog t6p10d1 run_report.txt listing.txt
call runprog t6p10d4 run_report.txt listing.txt
call runprog t6p1p2d4 run_report.txt listing.txt
call runprog t6p1p2d5 run_report.txt listing.txt
call runprog t6p1p2d6 run_report.txt listing.txt
call runprog t6p1p2d8 run_report.txt listing.txt
call runprog t6p1p5d13 run_report.txt listing.txt
call runprog t6p1p5d3 run_report.txt listing.txt
call runprog t6p1p5d4 run_report.txt listing.txt
call runprog t6p1p5d5 run_report.txt listing.txt
call runprog t6p1p5d6 run_report.txt listing.txt
call runprog t6p1p5d7 run_report.txt listing.txt
call runprog t6p1p6d4 run_report.txt listing.txt
call runprog t6p1p6d5 run_report.txt listing.txt
call runprog t6p1p6d6 run_report.txt listing.txt
call runprog t6p1p7d10 run_report.txt listing.txt
call runprog t6p1p7d11 run_report.txt listing.txt
call runprog t6p1p7d12 run_report.txt listing.txt
call runprog t6p1p7d13 run_report.txt listing.txt
call runprog t6p1p7d4 run_report.txt listing.txt
call runprog t6p1p7d5 run_report.txt listing.txt
call runprog t6p1p7d6 run_report.txt listing.txt
call runprog t6p1p7d7 run_report.txt listing.txt
call runprog t6p1p7d8 run_report.txt listing.txt
call runprog t6p1p7d9 run_report.txt listing.txt
call runprog t6p1p8d3 run_report.txt listing.txt
call runprog t6p1p8d4 run_report.txt listing.txt
call runprog t6p1p8d5 run_report.txt listing.txt
call runprog t6p1p9d4 run_report.txt listing.txt
call runprog t6p2p1d10 run_report.txt listing.txt
call runprog t6p2p1d4 run_report.txt listing.txt
call runprog t6p2p1d5 run_report.txt listing.txt
call runprog t6p2p1d6 run_report.txt listing.txt
call runprog t6p2p1d7 run_report.txt listing.txt
call runprog t6p2p1d8 run_report.txt listing.txt
call runprog t6p2p1d9 run_report.txt listing.txt
call runprog t6p2p2d10 run_report.txt listing.txt
call runprog t6p2p2d8 run_report.txt listing.txt
call runprog t6p2p2d9 run_report.txt listing.txt
call runprog t6p3d2 run_report.txt listing.txt
call runprog t6p3d3 run_report.txt listing.txt
call runprog t6p3d4 run_report.txt listing.txt
call runprog t6p3d5 run_report.txt listing.txt
call runprog t6p3d6 run_report.txt listing.txt
call runprog t6p3d7 run_report.txt listing.txt
call runprog t6p3d8 run_report.txt listing.txt
call runprog t6p3d9 run_report.txt listing.txt
call runprog t6p4p1d2 run_report.txt listing.txt
call runprog t6p4p1d3 run_report.txt listing.txt
call runprog t6p4p1d4 run_report.txt listing.txt
call runprog t6p4p2p2d9 run_report.txt listing.txt
call runprog t6p4p2p3d5 run_report.txt listing.txt
call runprog t6p4p2p3d6 run_report.txt listing.txt
call runprog t6p4p2p3d7 run_report.txt listing.txt
call runprog t6p4p2p4d3 run_report.txt listing.txt
call runprog t6p4p2p4d4 run_report.txt listing.txt
call runprog t6p4p2p4d5 run_report.txt listing.txt
call runprog t6p4p2p4d6 run_report.txt listing.txt
call runprog t6p4p3p1d3 run_report.txt listing.txt
call runprog t6p4p3p1d4 run_report.txt listing.txt
call runprog t6p4p3p1d5 run_report.txt listing.txt
call runprog t6p4p3p2d4 run_report.txt listing.txt
call runprog t6p4p3p2d5 run_report.txt listing.txt
call runprog t6p4p3p2d6 run_report.txt listing.txt
call runprog t6p4p3p2d9 run_report.txt listing.txt
call runprog t6p4p3p3d18 run_report.txt listing.txt
call runprog t6p4p3p3d19 run_report.txt listing.txt
call runprog t6p4p3p3d20 run_report.txt listing.txt
call runprog t6p4p3p3d8 run_report.txt listing.txt
call runprog t6p4p3p3d9 run_report.txt listing.txt
call runprog t6p4p3p4d3 run_report.txt listing.txt
call runprog t6p4p3p4d5 run_report.txt listing.txt
call runprog t6p4p3p4d6 run_report.txt listing.txt
call runprog t6p4p3p4d7 run_report.txt listing.txt
call runprog t6p4p4d2 run_report.txt listing.txt
call runprog t6p4p4d3 run_report.txt listing.txt
call runprog t6p4p5d10 run_report.txt listing.txt
call runprog t6p4p5d11 run_report.txt listing.txt
call runprog t6p4p5d12 run_report.txt listing.txt
call runprog t6p4p5d13 run_report.txt listing.txt
call runprog t6p4p5d14 run_report.txt listing.txt
call runprog t6p4p5d16 run_report.txt listing.txt
call runprog t6p4p5d7 run_report.txt listing.txt
call runprog t6p4p5d8 run_report.txt listing.txt
call runprog t6p4p5d9 run_report.txt listing.txt
call runprog t6p4p6d4 run_report.txt listing.txt
call runprog t6p4p6d5 run_report.txt listing.txt
call runprog t6p4p6d6 run_report.txt listing.txt
call runprog t6p4p6d7 run_report.txt listing.txt
call runprog t6p4p6d8 run_report.txt listing.txt
call runprog t6p6p1d3 run_report.txt listing.txt
call runprog t6p6p1d4 run_report.txt listing.txt
call runprog t6p6p1d5 run_report.txt listing.txt
call runprog t6p6p1d6 run_report.txt listing.txt
call runprog t6p6p1d7 run_report.txt listing.txt
call runprog t6p6p2d5 run_report.txt listing.txt
call runprog t6p6p2d6 run_report.txt listing.txt
call runprog t6p6p2d8 run_report.txt listing.txt
call runprog t6p6p3p1d5 run_report.txt listing.txt
call runprog t6p6p3p2d1 run_report.txt listing.txt
call runprog t6p6p3p2d2 run_report.txt listing.txt
call runprog t6p6p3p3d4 run_report.txt listing.txt
call runprog t6p6p3p3d5 run_report.txt listing.txt
call runprog t6p6p3p5d2 run_report.txt listing.txt
call runprog t6p6p3p6d1 run_report.txt listing.txt
call runprog t6p6p3p6d2 run_report.txt listing.txt
call runprog t6p6p3p6d3 run_report.txt listing.txt
call runprog t6p6p3p6d4 run_report.txt listing.txt
call runprog t6p6p3p6d5 run_report.txt listing.txt
call runprog t6p6p5p3d3 run_report.txt listing.txt
call runprog t6p6p6p1d1 run_report.txt listing.txt
call runprog t6p6p6p3d2 run_report.txt listing.txt
call runprog t6p6p6p4d4 run_report.txt listing.txt
call runprog t6p6p6p5d3 run_report.txt listing.txt
call runprog t6p6p6p5d4 run_report.txt listing.txt
call runprog t6p6p6p5d5 run_report.txt listing.txt
call runprog t6p6p6p5d9 run_report.txt listing.txt
call runprog t6p7p2p2d5 run_report.txt listing.txt
call runprog t6p7p2p2d6 run_report.txt listing.txt
call runprog t6p7p2p2d7 run_report.txt listing.txt
call runprog t6p7p2p3d2 run_report.txt listing.txt
call runprog t6p7p2p3d5 run_report.txt listing.txt
call runprog t6p7p2p4d3 run_report.txt listing.txt
call runprog t6p7p2p5d4 run_report.txt listing.txt
call runprog t6p7p2p5d5 run_report.txt listing.txt
call runprog t6p7p2p5d6 run_report.txt listing.txt
call runprog t6p7p2p5d7 run_report.txt listing.txt
call runprog t6p8p1d1 run_report.txt listing.txt
call runprog t6p8p1d2 run_report.txt listing.txt
call runprog t6p8p1d3 run_report.txt listing.txt
call runprog t6p8p1d4 run_report.txt listing.txt
call runprog t6p8p1d5 run_report.txt listing.txt
call runprog t6p8p2p3d1 run_report.txt listing.txt
call runprog t6p8p3p10d9 run_report.txt listing.txt
call runprog t6p8p3p5d3 run_report.txt listing.txt
call runprog t6p8p3p5d4 run_report.txt listing.txt
call runprog t6p8p3p5d5 run_report.txt listing.txt
call runprog t6p8p3p5d6 run_report.txt listing.txt
call runprog t6p8p3p5d7 run_report.txt listing.txt
call runprog t6p8p3p5d8 run_report.txt listing.txt
call runprog t6p8p3p5d9 run_report.txt listing.txt
call runprog t6p8p3p9d10 run_report.txt listing.txt
call runprog t6p8p3p9d11 run_report.txt listing.txt
call runprog t6p8p3p9d12 run_report.txt listing.txt
call runprog t6p8p3p9d13 run_report.txt listing.txt
call runprog t6p8p3p9d14 run_report.txt listing.txt
call runprog t6p8p3p9d15 run_report.txt listing.txt
call runprog t6p8p3p9d16 run_report.txt listing.txt
call runprog t6p8p3p9d17 run_report.txt listing.txt
call runprog t6p8p3p9d18 run_report.txt listing.txt
call runprog t6p8p3p9d5 run_report.txt listing.txt
call runprog t6p8p3p9d6 run_report.txt listing.txt
call runprog t6p8p3p9d7 run_report.txt listing.txt
call runprog t6p9p2d3 run_report.txt listing.txt
call runprog t6p9p3p2d1 run_report.txt listing.txt
call runprog t6p9p3p2d2 run_report.txt listing.txt
call runprog t6p9p4d3 run_report.txt listing.txt
call runprog t6p9p5d2 run_report.txt listing.txt
